# Generated by Django 2.2.15 on 2020-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200904_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body10',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body8',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body9',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='sampleimage1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sampleimage10',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sampleimage2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sampleimage3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sampleimage4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sampleimage5',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sampleimage6',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sampleimage7',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sampleimage8',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sampleimage9',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
